name: 'CI'

on:
  push:
    branches: ['develop']
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: Preparing timer
        id: timer_start
        run: |
          echo "DATE_START=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "TIMESTAMP_START=$(date +'%s')" >> $GITHUB_OUTPUT
      - name: 'Slack notification: IN PROGRESS'
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C068A06PV43'
          payload: |
            {
              "text": "CI Build Status for site-playground-cms-angular-bootstrap: IN PROGRESS\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":runner: CI Build Status for site-playground-cms-angular-bootstrap"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Start:* <!date^${{ steps.timer_start.outputs.TIMESTAMP_START }}^{date} at {time}|${{ steps.timer_start.outputs.DATE_START }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*End:* --"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:* IN PROGRESS"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":timer_clock: --"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Merge/Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build: ${{ github.run_id }}"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Run unit tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
      - name: Run lint
        run: ng lint
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Stopping timer
        if: ${{ !cancelled() }}
        id: timer_end
        env:
          TIMESTAMP_START: ${{ steps.timer_start.outputs.TIMESTAMP_START }}
        run: |
          echo "DATE_END=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "DURATION_PHRASE=$(($(date +'%s')-$TIMESTAMP_START)) seconds" >> $GITHUB_OUTPUT
          echo "TIMESTAMP_END=$(date +'%s')" >> $GITHUB_OUTPUT
      - name: 'Slack notification: Done'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C068A06PV43'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "CI Build Status for site-playground-cms-angular-bootstrap: DONE\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark: CI Build Status for site-playground-cms-angular-bootstrap"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Start:* <!date^${{ steps.timer_start.outputs.TIMESTAMP_START }}^{date} at {time}|${{ steps.timer_start.outputs.DATE_START }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*End:* <!date^${{ steps.timer_end.outputs.TIMESTAMP_END }}^{date} at {time}|${{ steps.timer_end.outputs.DATE_END }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:* Success"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":timer_clock: ${{ steps.timer_end.outputs.DURATION_PHRASE }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Merge/Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build: ${{ github.run_id }}"
                      },
                      "style": "primary",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: 'Send a notification for failures'
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C068A06PV43'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "CI Build Status for site-playground-cms-angular-bootstrap: FAILED\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":warning: CI Build Status for site-playground-cms-angular-bootstrap"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Start:* <!date^${{ steps.timer_start.outputs.TIMESTAMP_START }}^{date} at {time}|${{ steps.timer_start.outputs.DATE_START }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*End:* <!date^${{ steps.timer_end.outputs.TIMESTAMP_END }}^{date} at {time}|${{ steps.timer_end.outputs.DATE_END }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:* FAILED"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ":timer_clock: ${{ steps.timer_end.outputs.DURATION_PHRASE }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Merge/Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Build: ${{ github.run_id }}"
                      },
                      "style": "danger",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
